Ports clean_coords and its test
dartclub/turf_dart pull request #112
Opened 2022-07-05 13:13 UTC by armantorkzaban

2022-07-06 08:24 UTC, lukas-h requested changes

2022-07-06 08:24 UTC, lukas-h commented on lib/src/clean_coords.dart
> +/// [options.mutate=false] allows GeoJSON input to be mutated
it is just `mutate`

2022-07-06 20:41 UTC, armantorkzaban commented on lib/src/clean_coords.dart
> +  }
Does't line 54 suffice?

2022-07-06 20:48 UTC, armantorkzaban commented on lib/src/clean_coords.dart
> + * @param {boolean} [options.mutate=false] allows GeoJSON input to be mutated
Will do when I can test the function. Meanwhile keeping it as a reference.

2022-07-07 05:13 UTC, lukas-h requested changes

2022-07-07 05:13 UTC, lukas-h commented on lib/src/clean_coords.dart
> +    throw Exception("$geom is not supported");
Please use something like `${geom.type}`

2022-07-07 05:13 UTC, lukas-h commented on lib/src/clean_coords.dart
> +/// [options.mutate=false] allows GeoJSON input to be mutated
docs not changed yet.

2022-07-07 05:13 UTC, lukas-h commented on lib/src/clean_coords.dart
> +  }
Yes you are right

2022-07-07 05:13 UTC, lukas-h commented on lib/src/clean_coords.dart
> +equals(Position pt1, Position pt2) {
please don't resolve a conversation, if it is not done. Is there a reason we need this function?

2022-07-07 07:27 UTC, lukas-h commented
you can continue here, just merged #111

2022-07-07 19:36 UTC, lukas-h approved these changes

2022-07-07 19:37 UTC, merged