Port coordAll function and test
dartclub/turf_dart pull request #64
Opened 2022-03-15 15:15 UTC by armantorkzaban

2022-03-16 11:00 UTC, armantorkzaban commented
can we change the signature of CoordEachCallback's   CoordinateType? currentCoord,
 to Position? currentCoord?

2022-03-16 12:19 UTC, lukas-h requested changes

2022-03-16 12:19 UTC, lukas-h commented on lib/src/meta.dart
> +  //todo: can we change this Position
Yes, let's do it!

2022-03-16 12:19 UTC, lukas-h commented on lib/src/meta.dart
> +/// @Lukas: return Position or CoordinateType?
Let's use comments for that, not directly in the source code.

`Position?` is the right type. Please refactor coordAll and coordEach to use that type!

2022-03-16 21:10 UTC, lukas-h commented on lib/src/meta.dart
> +          if (callback(coords as Position, coordIndex, featureIndex,
is the typecast necessary anymore?

2022-03-17 06:46 UTC, lukas-h approved these changes

2022-03-18 06:49 UTC, lukas-h commented on lib/src/meta.dart
> +          if (callback(coords as Position, coordIndex, featureIndex,
Please resolve conversations, if it’s done!

2022-03-19 12:13 UTC, lukas-h commented
@armantorkzaban when is this PR mergeable?

2022-03-21 08:15 UTC, merged

2022-03-21 08:17 UTC, lukas-h commented
@armantorkzaban the merge conflict was only, because in the meantime I refactored coordEach in another branch that got merged first.